/*
gamepad.js, See README for copyright and usage instructions.
*/
(function(){var n=function(){this.dpadRight=this.dpadLeft=this.dpadDown=this.dpadUp=this.rightStickButton=this.leftStickButton=this.start=this.select=this.rightShoulder1=this.leftShoulder1=this.rightShoulder0=this.leftShoulder0=this.faceButton3=this.faceButton2=this.faceButton1=this.faceButton0=this.rightStickY=this.rightStickX=this.leftStickY=this.leftStickX=0;this.deadZoneRightStick=this.deadZoneLeftStick=0.25;this.deadZoneShoulder1=this.deadZoneShoulder0=0;this.images=f.ImageDataUrls_Unknown;this.name=
"Unknown"},i=navigator.userAgent,o=-1!=i.indexOf("Windows NT"),p=-1!=i.indexOf("Macintosh"),v=-1!=i.indexOf("Linux"),w=-1!=i.indexOf("CrOS"),m=-1!=i.indexOf("Chrome/");if(i=-1!=i.indexOf("Firefox/"))navigator.mozGamepads=[],window.addEventListener("MozGamepadConnected",function(b){navigator.mozGamepads[b.gamepad.index]=b.gamepad}),window.addEventListener("MozGamepadDisconnected",function(b){navigator.mozGamepads[b.gamepad.index]=void 0});var q=function(b,a){var e=b[a];if(e){void 0===j[a]&&(k[a]=new n,
j[a]=new n);var c=k[a],d=j[a];c.leftStickX=d.leftStickX;c.leftStickY=d.leftStickY;c.rightStickX=d.rightStickX;c.rightStickY=d.rightStickY;c.faceButton0=d.faceButton0;c.faceButton1=d.faceButton1;c.faceButton2=d.faceButton2;c.faceButton3=d.faceButton3;c.leftShoulder0=d.leftShoulder0;c.rightShoulder0=d.rightShoulder0;c.leftShoulder1=d.leftShoulder1;c.rightShoulder1=d.rightShoulder1;c.select=d.select;c.start=d.start;c.leftStickButton=d.leftStickButton;c.rightStickButton=d.rightStickButton;c.dpadUp=d.dpadUp;
c.dpadDown=d.dpadDown;c.dpadLeft=d.dpadLeft;c.dpadRight=d.dpadRight;a:{for(var c=j[a],d=g.length,h=0;h<d;++h){var f=g[h],i=f[1];if(-1!=e.id.indexOf(f[0])&&-1!=e.id.indexOf(i)){(0,f[2])(e,c);c.name=f[3]+" Player "+(e.index+1);c.images=f[4];break a}}c.name="Unknown: "+e.id;console.warn("Unrecognized pad type, not being mapped!");console.warn(e.id)}}else k[a]=void 0,j[a]=void 0},k=[],j=[],f={};window.Gamepad=f;f.getPreviousStates=function(){return k};f.getRawState=function(){var b=navigator.webkitGetGamepads||
navigator.mozGetGamepads||navigator.getGamepads,a=navigator.webkitGamepads||navigator.mozGamepads||navigator.gamepads;!a&&b&&(a=b.call(navigator));return a};f.getStates=function(){for(var b=f.getRawState(),a=b.length,e=0;e<a;++e)q(b,e);for(;e<j.length;++e)k[e]=void 0,j[e]=void 0;return j};f.getPreviousState=function(b){return k[b]};f.getState=function(b){var a=f.getRawState();q(a,b);return j[b]};f.supported=void 0!=(navigator.webkitGamepads||navigator.mozGamepads||navigator.gamepads)||void 0!=(navigator.webkitGetGamepads||
navigator.mozGetGamepads||navigator.getGamepads);var x=function(b,a){a.leftStickX=b.axes[0];a.leftStickY=b.axes[1];a.rightStickX=b.axes[2];a.rightStickY=b.axes[3];a.faceButton0=b.buttons[0];a.faceButton1=b.buttons[1];a.faceButton2=b.buttons[2];a.faceButton3=b.buttons[3];a.leftShoulder0=b.buttons[4];a.rightShoulder0=b.buttons[5];a.leftShoulder1=b.buttons[6];a.rightShoulder1=b.buttons[7];a.select=b.buttons[8];a.start=b.buttons[9];a.leftStickButton=b.buttons[10];a.rightStickButton=b.buttons[11];a.dpadUp=
b.buttons[12];a.dpadDown=b.buttons[13];a.dpadLeft=b.buttons[14];a.dpadRight=b.buttons[15];a.deadZoneLeftStick=7849/32767;a.deadZoneRightStick=8689/32767;a.deadZoneShoulder0=0.5;a.deadZoneShoulder1=30/255},l=function(b,a){a.leftStickX=b.axes[0];a.leftStickY=b.axes[1];a.rightStickX=b.axes[3];a.rightStickY=b.axes[4];a.faceButton0=b.buttons[0];a.faceButton1=b.buttons[1];a.faceButton2=b.buttons[2];a.faceButton3=b.buttons[3];a.leftShoulder0=b.buttons[4];a.rightShoulder0=b.buttons[5];a.leftShoulder1=0<b.axes[2]?
b.axes[2]:0;a.rightShoulder1=0>b.axes[2]?-b.axes[2]:0;a.select=b.buttons[6];a.start=b.buttons[7];a.leftStickButton=b.buttons[8];a.rightStickButton=b.buttons[9];a.dpadUp=-0.5>b.axes[6]?1:0;a.dpadDown=0.5<b.axes[6]?1:0;a.dpadLeft=-0.5>b.axes[5]?1:0;a.dpadRight=0.5<b.axes[5]?1:0;a.deadZoneLeftStick=7849/32767;a.deadZoneRightStick=8689/32767;a.deadZoneShoulder0=0.5;a.deadZoneShoulder1=30/255},r=function(b,a){a.leftStickX=b.axes[0];a.leftStickY=b.axes[1];a.rightStickX=b.axes[2];a.rightStickY=b.axes[3];
a.faceButton0=b.buttons[0];a.faceButton1=b.buttons[1];a.faceButton2=b.buttons[2];a.faceButton3=b.buttons[3];a.leftShoulder0=b.buttons[4];a.rightShoulder0=b.buttons[5];a.leftShoulder1=b.buttons[6];a.rightShoulder1=b.buttons[7];a.select=b.buttons[8];a.start=b.buttons[9];a.leftStickButton=b.buttons[10];a.rightStickButton=b.buttons[11];a.dpadUp=b.buttons[12];a.dpadDown=b.buttons[13];a.dpadLeft=b.buttons[14];a.dpadRight=b.buttons[15];a.deadZoneLeftStick=7849/32767;a.deadZoneRightStick=8689/32767;a.deadZoneShoulder0=
0.5;a.deadZoneShoulder1=30/255},s=function(b,a,e){r(b,a,e)},y=function(b,a,e){r(b,a,e)},z=function(b,a){a.leftStickX=raw.axes[0];a.leftStickY=raw.axes[1];a.rightStickX=raw.axes[2];a.faceButton0=raw.buttons[14];a.faceButton1=raw.buttons[13];a.faceButton2=raw.buttons[15];a.faceButton3=raw.buttons[12];a.leftShoulder0=raw.buttons[10];a.rightShoulder0=raw.buttons[11];a.leftShoulder1=raw.buttons[8];a.rightShoulder1=raw.buttons[9];a.select=raw.buttons[0];a.start=raw.buttons[3];a.leftStickButton=raw.buttons[1];
a.rightStickButton=raw.buttons[2];a.dpadUp=raw.buttons[4];a.dpadDown=raw.buttons[6];a.dpadLeft=raw.buttons[7];a.dpadRight=raw.buttons[5];a.rightStickY=b.axes[3]},A=function(b,a){a.rightStickY=b.axes[5]},B=function(b,a){a.leftStickX=b.axes[0];a.leftStickY=b.axes[1];a.faceButton0=b.buttons[1];a.faceButton1=b.buttons[2];a.faceButton2=b.buttons[0];a.faceButton3=b.buttons[3];a.leftShoulder0=b.buttons[4];a.rightShoulder0=b.buttons[5];a.select=b.buttons[8];a.start=b.buttons[9];a.leftStickButton=b.buttons[10];
a.rightStickButton=b.buttons[11];a.dpadUp=0;a.dpadDown=0;a.dpadLeft=0;a.dpadRight=0;a.deadZoneLeftStick=7849/32767;a.deadZoneRightStick=8689/32767;a.deadZoneShoulder0=0.5;a.deadZoneShoulder1=30/255;a.rightStickX=b.axes[2];a.rightStickY=b.axes[5];a.leftShoulder1=b.buttons[6];a.rightShoulder1=b.buttons[7]},t=function(b,a){a.leftStickX=b.axes[0];a.leftStickY=b.axes[1];a.rightStickX=b.axes[2];a.rightStickY=b.axes[3];a.faceButton0=b.buttons[0];a.faceButton1=b.buttons[1];a.faceButton2=b.buttons[2];a.faceButton3=
b.buttons[3];a.leftShoulder0=b.buttons[4];a.rightShoulder0=b.buttons[5];a.leftShoulder1=b.buttons[6];a.rightShoulder1=b.buttons[7];a.select=b.buttons[8];a.start=b.buttons[9];a.leftStickButton=b.buttons[10];a.rightStickButton=b.buttons[11];a.dpadUp=b.buttons[12];a.dpadDown=b.buttons[13];a.dpadLeft=b.buttons[14];a.dpadRight=b.buttons[15];a.xboxButton=b.buttons[16];a.deadZoneLeftStick=7849/32767;a.deadZoneRightStick=8689/32767;a.deadZoneShoulder0=0.5;a.deadZoneShoulder1=30/255},C=function(b,a){a.leftStickX=
b.axes[0];a.leftStickY=b.axes[1];a.rightStickX=b.axes[3];a.rightStickY=b.axes[4];a.faceButton0=b.buttons[0];a.faceButton1=b.buttons[1];a.faceButton2=b.buttons[2];a.faceButton3=b.buttons[3];a.leftShoulder0=b.buttons[4];a.rightShoulder0=b.buttons[5];a.leftShoulder1=0.5*b.axes[2]+0.5;a.rightShoulder1=0.5*b.axes[5]+0.5;a.select=b.buttons[6];a.start=b.buttons[7];a.xboxButton=b.buttons[8];a.leftStickButton=b.buttons[9];a.rightStickButton=b.buttons[10];a.dpadUp=-0.5>b.axes[7]?1:0;a.dpadDown=0.5<b.axes[7]?
1:0;a.dpadLeft=-0.5>b.axes[6]?1:0;a.dpadRight=0.5<b.axes[6]?1:0;a.deadZoneLeftStick=7849/32767;a.deadZoneRightStick=8689/32767;a.deadZoneShoulder0=0.5;a.deadZoneShoulder1=30/255},u={},h={},g=[];m&&o?g.push(["XInput ","GAMEPAD",x,"Xbox 360",h]):m&&p?(g.push(["Vendor: 045e","Product: 028e",s,"Xbox 360",h]),g.push(["Vendor: 045e","Product: 02a1",s,"Xbox 360",h]),g.push(["Vendor: 054c","Product: 0268",A,"Playstation 3",u]),g.push(["Vendor: 046d","Product: c216",B,"Logitech F310",h])):i&&o?(g.push(["45e-",
"28e-",l,"Xbox 360",h]),g.push(["45e-","2a1-",l,"Xbox 360",h]),g.push(["46d-","c21d-",l,"Logitech F310",h]),g.push(["46d-","c21e-",l,"Logitech F510",h])):i&&p?(g.push(["45e-","28e-",y,"Xbox 360",h]),g.push(["54c-","268-",z,"Playstation 3",u])):m&&v?(g.push(["Vendor: 045e","Product: 028e",t,"Xbox 360",h]),g.push(["Vendor: 045e","Product: 02a1",t,"Xbox 360",h])):w&&g.push(["Vendor: 0738","Product: b726",C,"Mad Catz, Inc. MadCatz Call of Duty GamePad",h])})();
</script>
<script src="rift.js">
<link href="/sxp.css" type="text/css" rel="stylesheet">
<script>
</head>
<body style="background-color:black" onload="initPage()">
<div id="container" style="position: absolute; top: 0px; left: 0px;">
<div id="text" style="border: 1px solid black; background-color: white; position: absolute; top: 810px; left: 0px; width: 1280px;">
<div style="width:504px; height:0px; position: absolute; top:399px; left:388px; background-color:red;"></div>
<div style="width:100px; height:100px; position: absolute; top:350px; left:338px; border: 0px green solid;"></div>
<div style="width:100px; height:100px; position: absolute; top:350px; left:842px; border: 0px green solid;"></div>
</body>
</html>